openapi: 3.0.0
info:
  title: GoFood-like Service API
  description: API documentation for the GoFood-like service
  version: 1.0.0
servers:
  - url: http://localhost:2431
paths:
  /:order_id:
    get:
      summary: get order details
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Order detail retrieved
          content:
            application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: integer
                user_id:
                  type: integer
                food_id:
                  type: integer
                quantity:
                  type: integer
                order_date:
                  type: datetime
                current_status:
                  type: string
        "404":
          description: Order not found
        "500":
          description: Internal server error
  /food:
    post:
      summary: Request an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                food_id:
                  type: integer
                quantity:
                  type: integer
      responses:
        "201":
          description: Request created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
        "400":
          description: Invalid credentials
        "404":
          description: Not found
        "500":
          description: Internal server error
    parameters:
      - name: accept
        in: query
        description: ID of a trip to be accepted
        required: false
        schema:
          type: integer
        style: form
        explode: true
      - name: reject
        in: query
        description: ID of a trip to be rejected
        required: false
        schema:
          type: integer
        style: form
        explode: true
      - name: complete
        in: query
        description: ID of a trip to be marked complete
        required: false
        schema:
          type: integer
        style: form
        explode: true
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
