openapi: 3.0.0
info:
  title: GoRide-like Service API
  description: API documentation for the GoRide-like service
  version: 1.0.0
servers:
  - url: http://localhost:2431
paths:
  /:trip_id:
    get:
      summary: get trip details
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Trip detail retrieved
          content:
            application/json:
            schema:
              type: object
              properties:
                trip_id:
                  type: integer
                user_id:
                  type: integer
                driver_id:
                  type: integer
                start_location:
                  type: string
                end_location:
                  type: string
                fare:
                  type: string
                trip_date:
                  type: string
                current_status:
                  type: string
        "404":
          description: Trip not found
        "500":
          description: Internal server error
  /trip:
    post:
      summary: Request a trip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                driver_id:
                  type: integer
                start_location:
                  type: string
                end_location:
                  type: string
                fare:
                  type: string
                trip_date:
                  type: string
      responses:
        "201":
          description: Request created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  trip_id:
                    type: integer
        "400":
          description: Invalid credentials
        "404":
          description: Driver not found
        "500":
          description: Internal server error
    parameters:
      - name: accept
        in: query
        description: ID of a trip to be accepted
        required: false
        schema:
          type: integer
        style: form
        explode: true
      - name: reject
        in: query
        description: ID of a trip to be rejected
        required: false
        schema:
          type: integer
        style: form
        explode: true
      - name: complete
        in: query
        description: ID of a trip to be marked complete
        required: false
        schema:
          type: integer
        style: form
        explode: true
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
